project_id = "wrjqheztddmazlifbzbi"

[functions.weekly-email-cron]
verify_jwt = false

[functions.sitemap]
verify_jwt = false

[functions.stripe-webhook]
verify_jwt = false

[functions.create-checkout]
verify_jwt = false

[functions.seed-test-users]
verify_jwt = false

[functions.admin-delete-user]
verify_jwt = false

[functions.facebook-oauth]
verify_jwt = false

[functions.generate-pdf-report]
verify_jwt = false

[functions.check-subscription]
verify_jwt = false

[functions.run-audit]
verify_jwt = false

[functions.get-audit-report]
verify_jwt = false

[functions.facebook-auth-login]
verify_jwt = false

[functions.paypal-checkout]
verify_jwt = false

[functions.esewa-checkout]
verify_jwt = false

[functions.send-audit-email]
verify_jwt = false

[functions.facebook-webhook]
verify_jwt = false

[functions.generate-ai-insights]
verify_jwt = false

[functions.share-report]
verify_jwt = false

[functions.get-public-report]
verify_jwt = false

[functions.auto-audit-cron]
verify_jwt = false
